<Project>
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Version>26.04.12</Version>
    <LangVersion>14</LangVersion>
    <Nullable>enable</Nullable>
    <NeutralLanguage>en</NeutralLanguage>
    <SourceRevisionId>$([System.DateTime]::UtcNow.ToString("yyMMddHHmmss"))</SourceRevisionId>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="PKHeX.Core">
      <HintPath>$(MSBuildThisFileDirectory)PKHeX.Core.AutoMod\deps\PKHeX.Core.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>
</Project>
